#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AcmeQuizzes.UI.Resource", IsApplication=true)]

namespace AcmeQuizzes.UI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::AcmeQuizzes.UI.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::AcmeQuizzes.UI.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int GoHome = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int GoInstructions = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int NumberOfQuestion = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int PreQuizStart = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int StartQuiz = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int admin = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int again = 2131099654;
			
			// aapt resource value: 0x7f060011
			public const int answers = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int button1 = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int home = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int questionNumber = 2131099664;
			
			// aapt resource value: 0x7f060002
			public const int questionsList = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int review = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int reviewQuestions = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int score = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int textView2 = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int textView4 = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Admin = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Finish = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Instructions = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PreQuiz = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Question = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Review = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Quiz = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int add = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int admin = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int again = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int home = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int instruction_text = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int instructions = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int intro = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int next = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int number_rule = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int pre_quiz = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int review = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int score = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int start = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
